{
  "classic": {
    "red": [
      "Sneeze dramatically",
      "React to stepping on a Lego",
      "Celebrate scoring a goal",
      "React to seeing a spider",
      "Greet your best friend after a year apart",
      "React to winning the lottery",
      "Stub your toe",
      "React to cold water in the shower",
      "Cheer for your team",
      "React to dropping your phone face down",
      "Laugh at a joke",
      "React to biting into something sour",
      "React to hearing your alarm on Monday",
      "Wave goodbye to someone leaving forever",
      "React to someone cutting in line"
    ],
    "yellow": [
      "Explain you are running late",
      "Ask your boss for a raise",
      "Tell someone they have food on their face",
      "Order coffee at a busy cafe",
      "Apologize for accidentally bumping into someone",
      "Explain a plot twist to a friend",
      "Greet a neighbor you barely know",
      "Complain about the weather",
      "Convince a friend to try a weird food",
      "Tell someone their outfit looks great",
      "Describe your weekend plans",
      "React to a boring meeting finally ending",
      "Explain why you are vegetarian",
      "Tell someone you forgot their birthday",
      "Recommend your favorite restaurant"
    ],
    "blue": [
      "Walk like you own the room",
      "Sit down after a very long day",
      "React to receiving an unexpected gift",
      "Show how you dance when no one is watching",
      "React to your team losing in the final second",
      "Show how you act at a library",
      "React to seeing a baby do something cute",
      "Walk into a surprise party thrown for you",
      "React to your food arriving at a restaurant",
      "Show how you act when you are trying to be sneaky",
      "React to finishing a really hard workout",
      "Show how you sit through a terrible movie",
      "React to seeing an old photo of yourself",
      "Walk like you are late but trying to look calm",
      "React to someone spoiling a show you have not watched"
    ]
  },
  "office": {
    "red": [
      "React to the printer jamming again",
      "React to your computer crashing before saving",
      "Celebrate getting a promotion",
      "React to a meeting being cancelled last minute",
      "React to someone eating your lunch from the fridge",
      "React to your boss calling you into their office",
      "React to getting cc'd on a 50-person email chain",
      "React to a coworker taking credit for your idea",
      "React to the WiFi going down during a presentation",
      "React to finally finishing a huge project"
    ],
    "yellow": [
      "Give feedback on someone's idea without hurting their feelings",
      "Explain to your boss why the deadline will be missed",
      "Ask a coworker to stop microwaving fish",
      "Introduce yourself at a networking event",
      "Decline a meeting that could have been an email",
      "Ask IT to reset your password for the third time this week",
      "Tell your team the project scope just doubled",
      "Pitch your idea to a room of skeptical executives",
      "Explain Agile to someone who has never heard of it",
      "Negotiate a deadline extension"
    ],
    "blue": [
      "Walk into Monday morning like you are ready",
      "Sit through a presentation about something you already know",
      "React to getting free snacks in the break room",
      "Show how you look on a video call when your camera is off",
      "React to getting a ping at 5:01pm on a Friday",
      "Walk into the office after working from home for a year",
      "React to your headphones running out of battery in an open office",
      "Show how you pretend to be busy when your boss walks by",
      "React to a surprise all-hands meeting",
      "Walk out of the office on your last day"
    ]
  },
  "kellogg": {
    "red": [
      "React to getting into your dream school",
      "React to a cold call you were not prepared for",
      "Celebrate finishing your last final exam",
      "React to your team missing a case competition deadline",
      "React to a recruiter ghosting you after five rounds",
      "React to getting a return offer",
      "React to someone presenting your slide deck out of order",
      "React to free food at a networking event",
      "React to finding out you are in the same cohort as your rival",
      "React to your group project partner going completely silent"
    ],
    "yellow": [
      "Explain your career pivot to a skeptical recruiter",
      "Give your elevator pitch at a speed networking event",
      "Tell your study group you did not do the reading",
      "Ask a professor a question when you clearly did not read the case",
      "Convince your team to use your framework for the case",
      "Explain why you chose your MBA program at a dinner party",
      "Give feedback to a teammate about their presentation skills",
      "Negotiate your signing bonus",
      "Tell your professor you need an extension",
      "Pitch your startup idea to a VC who has heard it all"
    ],
    "blue": [
      "Walk into a networking event where you know nobody",
      "Sit through a two-hour lecture on a topic you already know",
      "React to the career center sending you a job posting that is completely wrong for you",
      "Show how you act during a campus visit when you are trying to impress",
      "React to seeing your GPA for the first time",
      "Walk into your first day of class",
      "React to someone namedropping aggressively at a mixer",
      "Show how you look at 2am before a case competition",
      "React to your professor calling on you by name",
      "Walk across the stage at graduation"
    ]
  },
  "travel": {
    "red": [
      "React to missing your flight by five minutes",
      "React to your luggage not arriving at baggage claim",
      "React to seeing the Northern Lights for the first time",
      "React to your hotel room being double-booked",
      "React to tasting something unidentifiable at a street market",
      "React to losing your passport the night before departure",
      "React to turbulence on a flight",
      "Celebrate arriving in a country you have always wanted to visit",
      "React to the best meal of your life",
      "React to a travel companion snoring all night"
    ],
    "yellow": [
      "Ask for directions in a country where you don't speak the language",
      "Bargain at a market where haggling is expected",
      "Explain to customs why you are carrying so many snacks",
      "Order food from a menu you cannot read",
      "Ask your Airbnb host where the WiFi password is",
      "Convince your travel partner to try a sketchy-looking local restaurant",
      "Explain your travel itinerary to someone who thinks it is too ambitious",
      "Tell a fellow traveler about the best hidden gem you found",
      "Ask a local for a restaurant recommendation",
      "Complain about a long layover to a fellow passenger"
    ],
    "blue": [
      "Walk through an airport when you are extremely late for a flight",
      "Sit in a middle seat on a 14-hour flight",
      "React to getting upgraded to business class unexpectedly",
      "Show how you pack a suitcase the night before a trip",
      "React to seeing your hometown from the plane window on the way back",
      "Walk around a new city on your first morning there",
      "React to a stunning view at the top of a hike",
      "Show how you fall asleep on public transportation in a foreign country",
      "React to your travel buddy wanting to leave a place you love",
      "Walk through customs when you have nothing to declare but feel guilty anyway"
    ]
  },
  "movies": {
    "red": [
      "Dodge security lasers",
      "Duel with a lightsaber",
      "Outrun an avalanche",
      "Defuse a time bomb",
      "Hang from a cliff edge",
      "Leap from an explosion",
      "Bust down a locked door",
      "Cross a crumbling bridge",
      "Wrestle a wild bear",
      "Survive a spaceship crash",
      "Do a martial arts kick",
      "Drive a getaway car",
      "Block incoming arrows",
      "Scale a skyscraper",
      "Slide under a blast door"
    ],
    "yellow": [
      "Deliver a closing argument",
      "Cast a magic spell",
      "Pitch a startup idea",
      "Give a battle speech",
      "Reveal you are the villain",
      "Shout 'Nooo!' in slow motion",
      "Negotiate with a villain",
      "Confess love in the rain",
      "Brace a ship for impact",
      "Interrogate a spy",
      "Announce a plot twist",
      "Warn the city of a monster",
      "Fire your sidekick",
      "Read an ancient prophecy",
      "Deliver a witty one-liner"
    ],
    "blue": [
      "Conduct a movie score",
      "Spot an alien mothership",
      "Stare off into the sunset",
      "Discover a glowing artifact",
      "React to a mentor's betrayal",
      "Wake up from a nightmare",
      "Walk away from an explosion",
      "Assemble a weapon",
      "Enter a room coolly",
      "React to an AI takeover",
      "Spot the enemy approaching",
      "Suit up in heavy armor",
      "Collapse after saving the world",
      "Pose in a superhero cape",
      "Read a secret dossier"
    ]
  }
}
