export const ACTION_CARDS = {
  red: [
    "Dodge security lasers",
    "Duel with a lightsaber",
    "Outrun an avalanche",
    "Defuse a time bomb",
    "Hang from a cliff edge",
    "Leap from an explosion",
    "Bust down a locked door",
    "Cross a crumbling bridge",
    "Wrestle a wild bear",
    "Survive a spaceship crash",
    "Do a martial arts kick",
    "Drive a getaway car",
    "Block incoming arrows",
    "Scale a skyscraper",
    "Slide under a blast door"
  ],
  yellow: [
    "Deliver a closing argument",
    "Cast a magic spell",
    "Pitch a startup idea",
    "Give a battle speech",
    "Reveal you are the villain",
    "Shout 'Nooo!' in slow motion",
    "Negotiate with a villain",
    "Confess love in the rain",
    "Brace a ship for impact",
    "Interrogate a spy",
    "Announce a plot twist",
    "Warn the city of a monster",
    "Fire your sidekick",
    "Read an ancient prophecy",
    "Deliver a witty one-liner"
  ],
  blue: [
    "Conduct a movie score",
    "Spot an alien mothership",
    "Stare off into the sunset",
    "Discover a glowing artifact",
    "React to a mentor's betrayal",
    "Wake up from a nightmare",
    "Walk away from an explosion",
    "Assemble a weapon",
    "Enter a room coolly",
    "React to an AI takeover",
    "Spot the enemy approaching",
    "Suit up in heavy armor",
    "Collapse after saving the world",
    "Pose in a superhero cape",
    "Read a secret dossier"
  ]
};
