const ACTION_CARDS = {
  red: [
    "Sneeze dramatically",
    "React to stepping on a Lego",
    "Celebrate scoring a goal",
    "React to seeing a spider",
    "Greet your best friend after a year apart",
    "React to winning the lottery",
    "Stub your toe",
    "React to cold water in the shower",
    "Cheer for your team",
    "React to dropping your phone face down",
    "Laugh at a joke",
    "React to biting into something sour",
    "React to hearing your alarm on Monday",
    "Wave goodbye to someone leaving forever",
    "React to someone cutting in line",
  ],
  yellow: [
    "Explain you are running late",
    "Ask your boss for a raise",
    "Tell someone they have food on their face",
    "Order coffee at a busy café",
    "Apologize for accidentally bumping into someone",
    "Explain a plot twist to a friend",
    "Greet a neighbor you barely know",
    "Complain about the weather",
    "Convince a friend to try a weird food",
    "Tell someone their outfit looks great",
    "Describe your weekend plans",
    "React to a boring meeting finally ending",
    "Explain why you are vegetarian",
    "Tell someone you forgot their birthday",
    "Recommend your favorite restaurant",
  ],
  blue: [
    "Walk like you own the room",
    "Sit down after a very long day",
    "React to receiving an unexpected gift",
    "Show how you dance when no one is watching",
    "React to your team losing in the final second",
    "Show how you act at a library",
    "React to seeing a baby do something cute",
    "Walk into a surprise party thrown for you",
    "React to your food arriving at a restaurant",
    "Show how you act when you are trying to be sneaky",
    "React to finishing a really hard workout",
    "Show how you sit through a terrible movie",
    "React to seeing an old photo of yourself",
    "Walk like you are late but trying to look calm",
    "React to someone spoiling a show you haven't watched",
  ],
};
